<a href="https://colab.research.google.com/github/ULLYA-24001324/data-science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Part 1-Google Colab and Python
import numpy as np

In [ ]:
#1. Create a numpy array of size 2 x 2
a=np.array([[1,2],[1,3]])
print(a)

[[1 2]
 [1 3]]


In [ ]:
#2. Create a random numpy array of size 3 x 4
b=np.random.random((3,4))
print(b)

[[0.99264666 0.78664151 0.71964217 0.0970829 ]
 [0.12024948 0.54925482 0.42187735 0.58920881]
 [0.63042284 0.38006203 0.75141484 0.54778928]]


In [ ]:
#3. Create a numpy array of ones and a numpy array of zeroes
#zeros
zeros_array=np.zeros((3,3))
print(zeros_array)

#ones
ones_array=np.ones((3,3))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#4. Create a random numpy array of size 6x3 and transpose it
ori_array=np.random.random((6,3))
transposed_array=ori_array.T
print("Original array:\n")
print(ori_array)
print("\n")
print("Transposed array:\n")
print(transposed_array)

Original array:

[[0.09228343 0.12293165 0.64694969]
 [0.45420435 0.40126867 0.31669755]
 [0.47404786 0.72295086 0.32971963]
 [0.58807226 0.54228426 0.96018259]
 [0.30705262 0.33840944 0.50007163]
 [0.91604259 0.62036005 0.1807657 ]]


Transposed array:

[[0.09228343 0.45420435 0.47404786 0.58807226 0.30705262 0.91604259]
 [0.12293165 0.40126867 0.72295086 0.54228426 0.33840944 0.62036005]
 [0.64694969 0.31669755 0.32971963 0.96018259 0.50007163 0.1807657 ]]


In [ ]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
#get dimension from user
n=int(input("Enter n:"))
p=int(input("Enter p:"))
m=int(input("Enter m:"))

A=np.random.random((n,p))
B=np.random.random((p,m))
C=np.dot(A,B)

print("n x p: \n")
print(A,"\n")

print("p x m: \n")
print(B,"\n")

print("A • B: \n")
print(C)

Enter n:2
Enter p:3
Enter m:4
n x p: 

[[0.03867283 0.34537748 0.4110175 ]
 [0.9973224  0.1497491  0.07916184]] 

p x m: 

[[0.67301554 0.0915169  0.80908065 0.96805225]
 [0.17852557 0.77117365 0.62513379 0.18344868]
 [0.58194617 0.12524094 0.94297196 0.65843734]] 

A • B: 

[[0.32687619 0.32136145 0.63477455 0.37142563]
 [0.74401545 0.21666872 0.97517488 1.04505459]]
