<a href="https://colab.research.google.com/github/ULLYA-24001324/data-science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Part 1-Google Colab and Python
import numpy as np

In [ ]:
#1. Create a numpy array of size 2 x 2
a=np.array([[1,2],[1,3]])
print(a)

[[1 2]
 [1 3]]


In [ ]:
#2. Create a random numpy array of size 3 x 4
b=np.random.random((3,4))
print(b)

[[0.46651142 0.68962248 0.98689853 0.8759054 ]
 [0.00518693 0.00413983 0.74778628 0.46032498]
 [0.95563522 0.30063154 0.56715212 0.97764769]]


In [ ]:
#3. Create a numpy array of ones and a numpy array of zeroes
#zeros
zeros_array=np.zeros((3,3))
print(zeros_array)

#ones
ones_array=np.ones((3,3))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#4. Create a random numpy array of size 6x3 and transpose it
ori_array=np.random.random((6,3))
transposed_array=ori_array.T
print("Original array:\n")
print(ori_array)
print("\n")
print("Transposed array:\n")
print(transposed_array)

Original array:

[[0.1307007  0.50569427 0.22172467]
 [0.70765443 0.73783486 0.65632172]
 [0.21475639 0.05401382 0.44804889]
 [0.40454796 0.67028503 0.406294  ]
 [0.95976606 0.64305799 0.00995586]
 [0.62184742 0.60662158 0.43480965]]


Transposed array:

[[0.1307007  0.70765443 0.21475639 0.40454796 0.95976606 0.62184742]
 [0.50569427 0.73783486 0.05401382 0.67028503 0.64305799 0.60662158]
 [0.22172467 0.65632172 0.44804889 0.406294   0.00995586 0.43480965]]


In [ ]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
#get dimension from user
n=int(input("Enter n:"))
p=int(input("Enter p:"))
m=int(input("Enter m:"))

A=np.random.random((n,p))
B=np.random.random((p,m))
C=np.dot(A,B)

print("n x p: \n")
print(A,"\n")

print("p x m: \n")
print(B,"\n")

print("A • B: \n")
print(C)

Enter n:2
Enter p:3
Enter m:4
n x p: 

[[0.55901378 0.01725126 0.76994552]
 [0.00665265 0.61988672 0.06336706]] 

p x m: 

[[0.97250626 0.36691443 0.74128958 0.71551489]
 [0.23624892 0.43671207 0.20948888 0.64515796]
 [0.18446612 0.20911749 0.19345157 0.63654628]] 

A • B: 

[[0.68974886 0.37365313 0.56695221 0.90121842]
 [0.16460639 0.28640413 0.14704937 0.44502099]]
